ARG ns=quay.io/nitrate
ARG version=latest

FROM ${ns}/nitrate:base-${version}

ARG build_latest=no
# For mod_wsgi to store socket file.
# https://modwsgi.readthedocs.io/en/master/configuration-directives/WSGISocketPrefix.html#wsgisocketprefix
ARG wsgi_dir=/var/run/wsgi
ARG extra_requires="async,mysql,pgsql,bugzilla,socialauth"

LABEL name=Nitrate
LABEL license=GPLv2+
LABEL version="${version}"
LABEL maintainer="Chenxiong Qi <qcxhome@gmail.com>"
LABEL vendor=""
LABEL description="Nitrate is a new test plan, test run and test case management system, \
which is written in Python and Django (the Python web framework)."
LABEL io.github.nitrate.url="https://nitrate.readthedocs.io/"
LABEL io.github.nitrate.vcs-url="https://github.com/Nitrate/Nitrate"
LABEL io.github.nitrate.issues-url="https://github.com/Nitrate/Nitrateissues/"

RUN dnf update -y && \
    dnf --setopt=deltarpm=0 --setopt=install_weak_deps=false --nodocs \
        install -y httpd python3-mod_wsgi && \
    dnf clean all

RUN mkdir bootstrap ${wsgi_dir} && \
    chown apache:apache uploads ${wsgi_dir} && \
    sed -i -e 's/^#\(LoadModule mpm_prefork_module .\+\.so\)$/\1/' /etc/httpd/conf.modules.d/00-mpm.conf && \
    sed -i -e 's/^\(LoadModule mpm_event_module .\+\.so\)$/#\1/' /etc/httpd/conf.modules.d/00-mpm.conf

COPY product.py ./venv/lib64/python3.10/site-packages/tcms/settings/product.py
COPY httpd.conf /etc/httpd/conf/httpd.conf
ADD entrypoint.sh ./bootstrap/
RUN chmod 755 ./bootstrap/entrypoint.sh
EXPOSE 8080
USER apache
VOLUME ["/var/log/httpd", "/project/nitrate-config", "/project/uploads"]
ENTRYPOINT "/project/bootstrap/entrypoint.sh"
