ARG ns=quay.io/nitrate
ARG version=latest
FROM ${ns}/nitrate:base-${version}

LABEL name=Nitrate
LABEL component=worker
LABEL license=GPLv2+
LABEL maintainer="Chenxiong Qi <qcxhome@gmail.com>"
LABEL description="Nitrate worker image to run asynchronous tasks."

VOLUME ["/project/uploads"]
CMD ["/project/venv/bin/celery", "-A", "tcms", "worker", "-l", "INFO"]
