ARG base_image
FROM ${base_image:-registry.fedoraproject.org/fedora:35}

ARG version=latest
ARG released=yes
# For mod_wsgi to store socket file.
# https://modwsgi.readthedocs.io/en/master/configuration-directives/WSGISocketPrefix.html#wsgisocketprefix
ARG wsgi_dir=/var/run/wsgi
ARG extra_requires="async,mysql,pgsql,bugzilla,socialauth"

LABEL name=Nitrate
LABEL component=base
LABEL license=GPLv2+
LABEL version="${version}"
LABEL released="${released}"
LABEL maintainer="Chenxiong Qi <qcxhome@gmail.com>"
LABEL vendor=""
LABEL description="Nitrate is a new test plan, test run and test case management system, \
which is written in Python and Django (the Python web framework). Base image includes \
installed Nitrate."
LABEL io.github.nitrate.url="https://nitrate.readthedocs.io/"
LABEL io.github.nitrate.vcs-url="https://github.com/Nitrate/Nitrate"
LABEL io.github.nitrate.issues-url="https://github.com/Nitrate/Nitrate/issues/"

ENV PYTHONPATH=/nitrate-config
ENV DJANGO_SETTINGS_MODULE=tcms.settings.product

WORKDIR /project

ADD app.tar.gz app/
COPY provision-base.sh .

RUN chmod u+x provision-base.sh && ./provision-base.sh && rm provision-base.sh

# SQLite database file could be placed in this volume
VOLUME ["/project/data"]
