ARG ns=quay.io/nitrate
ARG version=latest
FROM ${ns}/base:${version}

LABEL org.opencontainers.image.description="Nitrate worker image to run asynchronous tasks."

WORKDIR /project
COPY product.py ./venv/lib64/python3.11/site-packages/tcms/settings/product.py

VOLUME ["/project/uploads"]
CMD ["/project/venv/bin/celery", "-A", "tcms", "worker", "-l", "INFO"]
