version: "3"

# Please note that, this container-compose is only for test latest image built
# from development branch and prod image built from released version.

services:
  db:
    image: "mariadb:10.11.8"
    volumes:
    - "nitrate_db_data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_DATABASE: nitrate
      MYSQL_ROOT_PASSWORD: nitrate
    command: >-
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: mysqladmin ping -uroot -pnitrate
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s

  messagebus:
    image: rabbitmq:3.13.3-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_VHOST: myvhost
    healthcheck:
      test: rabbitmq-diagnostic -q ping
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  worker:
    depends_on:
    - messagebus
    restart: always
    image: "${NS:-quay.io/nitrate}/worker:${VERSION:-develop}"
    volumes:
    - "./compose/custom_settings.py:/project/nitrate-config/nitrate_custom_conf.py:Z"
    environment:
      NITRATE_DB_ENGINE: mysql
      NITRATE_DB_HOST: db
      NITRATE_DB_PORT: 3306
      NITRATE_DB_NAME: nitrate
      NITRATE_DB_USER: root
      NITRATE_SECRET_KEY: do-not-use-this-key-for-worker-production

  web:
    depends_on:
    - db
    - messagebus
    restart: always
    image: "${NS:-quay.io/nitrate}/web:${VERSION:-develop}"
    ports:
    - "8001:8080"
    volumes:
    - "./compose/custom_settings.py:/project/nitrate-config/nitrate_custom_conf.py:Z"
    - "nitrate_uploads:/code/uploads:Z"
    - "nitrate_httpd_logs:/var/log/httpd:Z"
    environment:
      NITRATE_DB_ENGINE: mysql
      NITRATE_DB_HOST: db
      NITRATE_DB_PORT: 3306
      NITRATE_DB_NAME: nitrate
      NITRATE_DB_USER: root
      NITRATE_SECRET_KEY: do-not-use-this-key-for-production
      NITRATE_MIGRATE_DB: 1
      NITRATE_SET_DEFAULT_PERMS: 1
      NITRATE_SUPERUSER_USERNAME: admin
      NITRATE_SUPERUSER_PASSWORD: admin
      NITRATE_SUPERUSER_EMAIL: admin@example.com
    healthcheck:
      test: curl -L http://127.0.0.1:8080 | grep "<title>Nitrate</title>"
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s


# Run `docker inspect web` to see volume directory on host.

volumes:
  nitrate_db_data:
  nitrate_uploads:
  nitrate_httpd_logs:
