ARG ns=quay.io/nitrate
ARG version=latest
FROM ${ns}/nitrate:base-${version}

# For mod_wsgi to store socket file.
# https://modwsgi.readthedocs.io/en/master/configuration-directives/WSGISocketPrefix.html#wsgisocketprefix
ARG wsgi_dir=/var/run/wsgi
ARG extra_requires="async,mysql,pgsql,bugzilla,socialauth"

LABEL name=Nitrate
LABEL component=web
LABEL license=GPLv2+
LABEL maintainer="Chenxiong Qi <qcxhome@gmail.com>"
LABEL description="Nitrate is a new test plan, test run and test case management system, \
which is written in Python and Django (the Python web framework)."

RUN dnf update -y && \
    dnf --setopt=deltarpm=0 --setopt=install_weak_deps=false --nodocs \
        install -y httpd python3-mod_wsgi && \
    dnf clean all

RUN mkdir bootstrap ${wsgi_dir} && \
    chown apache:apache uploads ${wsgi_dir} && \
    sed -i -e 's/^#\(LoadModule mpm_prefork_module .\+\.so\)$/\1/' /etc/httpd/conf.modules.d/00-mpm.conf && \
    sed -i -e 's/^\(LoadModule mpm_event_module .\+\.so\)$/#\1/' /etc/httpd/conf.modules.d/00-mpm.conf

WORKDIR /project
COPY product.py ./venv/lib64/python3.10/site-packages/tcms/settings/product.py
COPY httpd.conf /etc/httpd/conf/httpd.conf
COPY entrypoint.sh .
RUN chmod 755 entrypoint.sh
EXPOSE 8080
USER apache
VOLUME ["/var/log/httpd", "/project/nitrate-config", "/project/uploads"]
ENTRYPOINT ["./entrypoint.sh"]
