name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint_markdown:
    name: Lint markdown files
    runs-on: ubuntu-latest
    steps:
      - name: Install packages to provision environment
        run: |
          sudo apt-get update
          sudo apt-get install -y npm make
      - name: Install linter tool
        run: |
          mkdir ~/npm
          cd ~/npm
          npm install markdownlint-cli2
      - name: Get the code
        uses: actions/checkout@v3
      - name: Run linter
        run: |
          PATH=~/npm/node_modules/.bin:$PATH make lint-markdown

  lint_dockerfile:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Install packages to provision environment
        run: |
          sudo apt-get install -y curl make
          [ -e ~/.local/bin ] || mkdir -p ~/.local/bin
          cd ~/.local/bin
          curl -L -O https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64
          mv hadolint-Linux-x86_64 hadolint
          chmod u+x hadolint
      - uses: actions/checkout@v3
      - name: Run linter
        run: |
          PATH=~/.local/bin:$PATH make lint-dockerfile
