name: Test Images

on:
  pull_request:
    branches:
      - main

jobs:
  build_develop:
    name: Build from develop branch and push
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y make git
      - uses: actions/checkout@v3
      - name: Log into registry
        run: |
          echo "${{ secrets.quay_token }}" | \
              docker login -u "${{ secrets.quay_username }}" --password-stdin quay.io
      - run: |
          make all-images push-all engine=docker ns=quay.io/nitratecontainerstest

  build_release:
    name: Build from a release and push
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y make git
      - uses: actions/checkout@v3
      - name: Log into registry
        run: |
          echo "${{ secrets.quay_token }}" | \
              docker login -u "${{ secrets.quay_username }}" --password-stdin quay.io
      - run: |
          make all-images push-all \
              engine=docker ns=quay.io/nitratecontainerstest version=4.11

  build_based_on_f36:
    name: Test build development version based on Fedora 36 only
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y make git
      - uses: actions/checkout@v3
      - run: |
          make all-images \
            engine=docker \
            baseimage=registry.fedoraproject.org/fedora:36 \
            ns=quay.io/nitratecontainerstest
